doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        resolve_target_entities:
            Pd\WidgetBundle\Entity\UserInterface: App\Admin\Entity\Account\User
        mappings:
            Admin:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Admin/Entity'
                prefix: 'App\Admin\Entity'
                alias: Admin
