pd_user:
    user_class: App\Admin\Entity\Account\User
    profile_class: App\Admin\Entity\Account\Profile
    group_class: App\Admin\Entity\Account\Group
    default_group: ''
    login_redirect: 'web_home'
    email_confirmation: true
    welcome_email: true
    template_path: '@Auth'
    resetting_request_time: 7200
    active_language: "%active_language%"
