##
# Authorization Routing
##
authorization:
    resource: "@PdUserBundle/Resources/config/routing.yaml"
    prefix: 'auth'

##
# Admin Routing
##
admin:
    resource: "../src/Admin/Resources/config/routing.yaml"
    prefix: "/%routing_admin%"

##
# PD Mailer Bundle
##
admin_mailer:
    resource: "@PdMailerBundle/Resources/config/routing.yaml"
    prefix: "/%routing_admin%"

##
# Website Frontend Routing
##
web:
    resource: "../src/Web/Resources/config/routing.yaml"
    prefix: /
