imports:
    - { resource: "parameters.yaml" }
    - { resource: "../src/Auth/Resources/config/services.yaml" }
    - { resource: "../src/Web/Resources/config/services.yaml" }
    - { resource: "../src/Admin/Resources/config/services.yaml" }
