# Login - Logout
security_login:
    path: "/%routing_login%"
    controller: App\Auth\Controller\SecurityController::login
security_logout:
    path: "/%routing_logout%"

# Register
security_register:
    path: "/%routing_register%"
    controller: App\Auth\Controller\SecurityController::register
security_register_confirm:
    path: "/%routing_register%/{token}"
    controller: App\Auth\Controller\SecurityController::registerConfirm

# Resetting
security_resetting:
    path: "/%routing_resetting%"
    controller: App\Auth\Controller\SecurityController::resetting
security_resetting_password:
    path: "/%routing_resetting%/{token}"
    controller: App\Auth\Controller\SecurityController::resettingPassword