###
# Dashboard Controller
###
admin_dashboard:
    path:       /
    controller: App\Admin\Controller\DashboardController::index
admin_clear_cache:
    path:       /refresh/cache
    controller: App\Admin\Controller\DashboardController::clearCache

# Widget Routing
widget:
    resource: "@PdWidgetBundle/Resources/config/routing.yml"

##
## Account Controller
##
admin_account_list:
    path:       /accounts
    controller: App\Admin\Controller\Account\AccountController::list
    methods: [GET, POST]
admin_account_edit:
    path:       /accounts/edit/{user}
    controller: App\Admin\Controller\Account\AccountController::edit
    methods: [GET, POST]
admin_account_changepassword:
    path:       /accounts/changepassword/{user}
    controller: App\Admin\Controller\Account\AccountController::changePassword
    methods: [GET, POST]
admin_account_roles:
    path:       /accounts/roles/{user}
    controller: App\Admin\Controller\Account\AccountController::roles
    methods: [GET, POST]
admin_account_addgroup:
    path:       /accounts/addGroup/{user}
    controller: App\Admin\Controller\Account\AccountController::addGroup
    methods: [GET, POST]
admin_account_activate:
    path:       /accounts/activate/{user}/{status}
    controller: App\Admin\Controller\Account\AccountController::activate
    methods: [GET, POST]
admin_account_delete:
    path:       /accounts/delete/{user}
    controller: App\Admin\Controller\Account\AccountController::delete
    methods: [GET, POST]

##
## Account -> Group Controller
##
admin_account_group_list:
    path:       /accounts/group
    controller: App\Admin\Controller\Account\GroupController::list
    methods: [GET, POST]
admin_account_group_edit:
    path:       /accounts/group/edit/{group}
    controller: App\Admin\Controller\Account\GroupController::edit
    methods: [GET, POST]
admin_account_group_roles:
    path:       /accounts/group/roles/{group}
    controller: App\Admin\Controller\Account\GroupController::roles
    methods: [GET, POST]
admin_account_group_new:
    path:       /accounts/group/new
    controller: App\Admin\Controller\Account\GroupController::new
    methods: [GET, POST]
admin_account_group_delete:
    path:       /accounts/group/delete/{group}
    controller: App\Admin\Controller\Account\GroupController::delete
    methods: [GET, POST]

###
# Settings
###
admin_settings_general:
    path:       /settings
    controller: App\Admin\Controller\System\SettingsController::general
admin_settings_contact:
    path:       /settings/contact
    controller: App\Admin\Controller\System\SettingsController::contact
admin_settings_email:
    path:       /settings/email
    controller: App\Admin\Controller\System\SettingsController::email
admin_settings_user:
    path:       /settings/user
    controller: App\Admin\Controller\System\SettingsController::user
admin_settings_media:
    path:       /settings/media
    controller: App\Admin\Controller\System\SettingsController::media
admin_settings_template:
    path:       /settings/template
    controller: App\Admin\Controller\System\SettingsController::template
admin_settings_core:
    path:       /settings/core
    controller: App\Admin\Controller\System\SettingsController::core
admin_settings_routing:
    path:       /settings/routing
    controller: App\Admin\Controller\System\SettingsController::routing

###
# Settings -> Mail
###
admin_mail_list:
    path:   /settings/mail
    controller: App\Admin\Controller\System\MailController::list
    methods: [GET]
admin_mail_template_add:
    path: /settings/mail/add/{id}
    controller: App\Admin\Controller\System\MailController::addMailTemplate
    methods: [GET, POST]
admin_mail_template_edit:
    path: /settings/mail/edit/{id}
    controller: App\Admin\Controller\System\MailController::editMailTemplate
    methods: [GET, POST]
admin_mail_template_delete:
    path: /settings/mail/delete/{id}
    controller: App\Admin\Controller\System\MailController::deleteMailTemplate
    methods: [GET]
admin_mail_template_activate:
    path: /settings/mail/activate/{id}
    controller: App\Admin\Controller\System\MailController::activateMailTemplate
    methods: [GET]
admin_mail_logger:
    path:   /settings/mail/logger
    controller: App\Admin\Controller\System\MailController::logger
    methods: [GET]
admin_mail_logview:
    path:   /settings/mail/logview/{id}
    controller: App\Admin\Controller\System\MailController::viewLog
    methods: [GET]
admin_mail_logdelete:
    path:   /settings/mail/logdelete/{mailLog}
    controller: App\Admin\Controller\System\MailController::deleteLog
    defaults:
        mailLog: null
    methods: [POST,GET]
admin_mail_default_template:
    path: /settings/mail/defaulttemplate/{templateId}
    controller: App\Admin\Controller\System\MailController::defaultTemplate
    methods: [GET, POST]
